Enable transciever delay to fix USB334x
stm32-rs/synopsys-usb-otg pull request #17
Opened 2021-03-25 21:32 UTC by mattico

The Microchip USB334x PHYs have an errata related to the ULPI protocol:

![image](https://user-images.githubusercontent.com/853158/112545402-2cb31500-8d86-11eb-9578-c5d611b83d21.png)

So the PHY doesn't do the device chirp and thus doesn't enumerate as a HS device. Since this crate doesn't support using ULPI HS-in-FS mode, the device descriptors are valid only for HS mode and the device configuration fails. The solution is to enable `XCVRDLY` in OTG_DCFG.

The Xilinix Zynq datasheet [has a bit more information than the STM32H7 one](https://forums.xilinx.com/t5/Embedded-Linux/USB-stuck-in-full-speed-mode-with-USB3340-ULPI-PHY-ZynqMP/td-p/1046535) which is presumably relevant:

> XCVRDLY - Transceiver Delay:
Enables a delay between the assertion of the UTMI/ULPI Transceiver Select signal (for HS) and the assertion of the TxValid signal during a HS Chirp.
When this bit is set to 1, a delay (of approximately 2.5 us) is introduced from the time when the Transceiver Select is set to 2'b00 (HS) to the time the TxValid is driven to 0 for sending the chirp-K. This delay is required for some UTMI/ULPI PHYs.
Note:
>- If you enable the hibernation feature when the device core comes out of power-off, you must re-initialize this bit with the appropriate value because the core does not save and restore this bit value during hibernation.
>- This bit is valid only in device mode.

We could make this configurable on the off chance that some device/PHY doesn't handle this option well.

2021-04-20 12:04 UTC, Disasm commented
I think it's a good idea to make a method on `UsbBus` that will enable this workaround. Also `XCVRDLY` field is not present in F429-like IP-cores.

2021-04-22 18:44 UTC, Disasm commented on src/bus.rs
> +                XCVRDLY: self.xcvrdly as u32,
I'd suggest not touching this field if the flag is `false`. Who knows what is stored there in IP core versions that doesn't have this field.

2021-04-22 18:55 UTC, Disasm requested changes

2021-04-22 18:55 UTC, Disasm commented on src/lib.rs
> +    fn use_transceiver_delay(&self) -> bool {
This shouldn't be a trait method as this workaround fixes a specific problem with an external PHY chip, and HALs that implement the trait know nothing about the PHY. `UsbBus` method that enables the workaround was a good option.

2021-04-22 18:56 UTC, mattico commented on src/lib.rs
> +    fn use_transceiver_delay(&self) -> bool {
Hm, I made this a function rather than a constant because maybe a HAL would want to conditionally enable this only for the PHYs that need it, but the HAL can't determine what PHY is connected until after the ULPI bus is enabled in `enable()` and at that point it's already too late. The HAL would have to enable at compile time with a flag but in that case an associated constant would work.

2021-05-07 23:53 UTC, mattico commented on src/lib.rs
> +    fn use_transceiver_delay(&self) -> bool {
The issue is that the `UsbBus` isn't accessible until after the `UsbDevice` is built, which causes the device to enable/connect. The transciever delay should be enabled before connecting. Could `UsbBusAllocator` provide a getter for the `UsbBus`?

Alternatively it might work to `build()` then `use_transciever_delay()` then `force_reset()`, I'll have to test that.

2021-12-27 21:17 UTC, mattico commented
I've changed the method to enable transceiver delay to be a cargo feature, which should work in the vast majority of cases where you know if it is safe to enable on your target platform at compile time.

2022-01-04 18:17 UTC, Disasm approved these changes
Sorry for the delay, let's merge this PR. Thank you for the update!

2022-01-04 18:18 UTC, merged